# Generated by Django 6.0 on 2025-12-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_brand_alter_car_id_alter_car_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="brand",
            new_name="brand_id",
        ),
    ]
