# Generated by Django 6.0 on 2025-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_rename_brand_car_brand_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
